kotlin.code.style=official


kotlinVersion=2.2.20

# 1.8 -> Kotlin 1.9, 1.9 -> Kotlin 2.0, 1.10 -> Kotlin 2.1
coroutinesVersion=1.9.0


quarkusVersion=3.24.5
#quarkusVersion=3.20.2.2
#quarkusVersion=3.15.6


maxMindDbVersion=3.2.0
maxMindGeoIpVersion=4.3.1

apacheCompressVersion=1.28.0

webClientVersion=1.7.0
jacksonVersion=2.20.0

klfVersion=1.8.3
logFormatterVersion=2.0.1
lokiLoggerVersion=0.8.0


# for tests
assertKVersion=0.28.1
