####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a micro base image, tuned for Quarkus native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
#
# Before building the container image run:
#
# ./gradlew build -Dquarkus.native.enabled=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-micro -t quarkus/geo-ip-api .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/geo-ip-api
#
# The `quay.io/quarkus/ubi9-quarkus-micro-image:2.0` base image is based on UBI 9.
# To use UBI 8, switch to `quay.io/quarkus/quarkus-micro-image:2.0`.
###
FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0

# create directory for app data (where e.g. by default downloaded GeoIP database files are stored)
USER 0
RUN mkdir -p /var/lib/geoip \
    && chgrp -R 0 /var/lib/geoip \
    && chmod -R g=u /var/lib/geoip

USER 1001

ENV GEOIP_DATA_FOLDER=/var/lib/geoip

VOLUME ["/var/lib/geoip"]


WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --chmod=0755 build/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
