
quarkus.application.name=GeoIpApi


%dev.quarkus.http.host=0.0.0.0
%dev.quarkus.http.port=8097

# during development enable CORS
quarkus.http.cors.enabled=${GEOIP_CORS_ENABLED:false}
%dev.quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${GEOIP_CORS_ORIGINS:*}

# enable GZip
quarkus.http.enable-compression=true
quarkus.http.enable-decompression=true

# log request response times
quarkus.http.access-log.enabled=${GEOIP_ACCESS_LOG_ENABLED:false}
%dev.quarkus.http.access-log.enabled=true
quarkus.http.record-request-start-time=true
quarkus.http.access-log.exclude-pattern=/metrics|/health.*|.*/swagger-ui/.+\.(css|js)|.*/health-ui/.+\.(png|css|js)
# for all variables see: https://quarkus.io/guides/http-reference#configuring-http-access-logs
# %h Remote host name
# %s HTTP status code of the response
# %D Time taken to process the request, in millis
# %r First line of the request
# %b Bytes sent, excluding HTTP headers, or '-' if no bytes were sent
quarkus.http.access-log.pattern=%{i,X-Forwarded-For} %h %s %D ms "%r" %b bytes %{i,User-Agent}


# Logging

# would be way nicer, but Fluentd cannot cope with AnsiColors
#quarkus.console.color=true
quarkus.log.console.async.enable=true

quarkus.log.console.stacktrace.root-cause-first=true
%prod.quarkus.log.console.stacktrace.max-frames-per-throwable=5
%prod.quarkus.log.console.stacktrace.max-nested-throwables=0


quarkus.log.loki.enable=${GEOIP_LOKI_ENABLE:false}
quarkus.log.loki.baseUrl=${GEOIP_LOKI_BASEURL: }
%dev.quarkus.log.loki.enable=true
%dev.quarkus.log.loki.baseUrl=http://localhost:3100

%prod.quarkus.log.loki.field.kubernetes.include=true
quarkus.log.loki.field.kubernetes.nodename.include=label


# Live reload

quarkus.live-reload.instrumentation=true

# disable this output:
# Press [h] for more options>
# Tests paused
# Press [r] to resume testing, [h] for more options>
# Press [r] to resume testing, [o] Toggle test output, [h] for more options>
quarkus.test.continuous-testing=disabled
quarkus.console.disable-input=true

# disable Analytics
quarkus.analytics.disabled=true


# Quarkus Native settings


# GeoIP

geoip.data-folder=${GEOIP_DATA_FOLDER:/var/lib/geoip}
%dev.geoip.data-folder=${GEOIP_DATA_FOLDER:/tmp/geoip}

geoip.geolite2.download=${GEOIP_GEOLITE2_DOWNLOAD:true}
geoip.iplocate.download=${GEOIP_IPLOCATE_DOWNLOAD:true}


# Metrics and Health

# Kubernetes / Prometheus won't find endpoints under /q/health, /q/metrics, ..., so remove /q (= Quarkus default sub path) from path
quarkus.micrometer.export.prometheus.path=/metrics

quarkus.smallrye-health.root-path=/health
quarkus.smallrye-health.startup-path=startup
quarkus.smallrye-health.openapi.included=true


# OpenAPI and Swagger-UI

# so that in Kubernetes Swagger-UI, Health UI, ... can be reached under /geoip (under /q/ it's not reachable via ingress)
quarkus.http.root-path=/geoip
# serve Svelte app in resources/META-INF/resources from same path as quarkus.http.root-path
quarkus.http.non-application-root-path=${quarkus.http.root-path}

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.enable=${GEOIP_SWAGGER_UI_ENABLE:false}
%dev.quarkus.swagger-ui.enable=true
quarkus.swagger-ui.theme=flattop
quarkus.swagger-ui.try-it-out-enabled=true
quarkus.swagger-ui.query-config-enabled=true
quarkus.swagger-ui.display-request-duration=true

quarkus.smallrye-openapi.info-title=GeoIP API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API to access information to an IP address like ASN, City or Country
quarkus.smallrye-openapi.info-contact-email=dev@codinux.net